-- Mystery Box 3D — Reward claim + admin controls
-- ONLY adds the reward-claim workflow and admin coin controls.
-- Does not delete or alter existing player/topup/history tables.

-- ============================================================
-- 1) PLAYER REWARD CLAIM REQUESTS
-- ============================================================
create table if not exists public.reward_claim_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  items jsonb not null default '[]'::jsonb,
  status text not null default 'pending'
    check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id)
);

create index if not exists reward_claim_requests_status_created_idx
on public.reward_claim_requests(status, created_at desc);

alter table public.reward_claim_requests enable row level security;

drop policy if exists "reward_claim_requests_select_own" on public.reward_claim_requests;
create policy "reward_claim_requests_select_own"
on public.reward_claim_requests for select
to authenticated
using (auth.uid() = user_id);

grant select on public.reward_claim_requests to authenticated;

-- ============================================================
-- 2) PLAYER: SEND REWARD(S) TO ADMIN
--    The database moves the selected rewards out of the
--    player's inventory atomically, so refresh cannot lose them.
-- ============================================================
drop function if exists public.submit_reward_claim(jsonb);

create function public.submit_reward_claim(p_item_ids jsonb default '[]'::jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_items jsonb := '[]'::jsonb;
  v_remaining jsonb := '[]'::jsonb;
  v_claim_id bigint;
  v_inventory_id uuid;
  v_requested jsonb := coalesce(p_item_ids, '[]'::jsonb);
begin
  if v_user_id is null then
    raise exception 'not_authenticated';
  end if;

  if jsonb_typeof(v_requested) <> 'array' then
    raise exception 'invalid_item_ids';
  end if;

  select pi.user_id, coalesce(pi.items, '[]'::jsonb)
    into v_inventory_id, v_items
  from public.player_inventory pi
  where pi.user_id = v_user_id
  for update;

  if v_inventory_id is null then
    raise exception 'inventory_not_found';
  end if;

  -- Empty list = request the entire current inventory.
  if jsonb_array_length(v_requested) = 0 then
    v_remaining := '[]'::jsonb;
  else
    select coalesce(jsonb_agg(item order by ord), '[]'::jsonb)
      into v_items
    from jsonb_array_elements(v_items) with ordinality as x(item, ord)
    where (item->>'id') in (
      select jsonb_array_elements_text(v_requested)
    );

    if jsonb_array_length(v_items) = 0 then
      raise exception 'reward_not_found';
    end if;

    select coalesce(jsonb_agg(item order by ord), '[]'::jsonb)
      into v_remaining
    from jsonb_array_elements(
      (select pi2.items from public.player_inventory pi2 where pi2.user_id=v_user_id)
    ) with ordinality as x(item, ord)
    where not ((item->>'id') in (
      select jsonb_array_elements_text(v_requested)
    ));
  end if;

  -- For "all", v_items was not populated above because it was read
  -- from inventory before the branch; v_items already contains all.
  if jsonb_array_length(v_requested) = 0 then
    select coalesce(pi.items, '[]'::jsonb)
      into v_items
    from public.player_inventory pi
    where pi.user_id = v_user_id;
    if jsonb_array_length(v_items) = 0 then
      raise exception 'no_rewards_to_claim';
    end if;
  end if;

  insert into public.reward_claim_requests(user_id, items)
  values (v_user_id, v_items)
  returning id into v_claim_id;

  update public.player_inventory
  set items = v_remaining,
      updated_at = now()
  where user_id = v_user_id;

  return jsonb_build_object(
    'claim_id', v_claim_id,
    'remaining_items', v_remaining
  );
end;
$$;

revoke all on function public.submit_reward_claim(jsonb) from public;
grant execute on function public.submit_reward_claim(jsonb) to authenticated;

-- ============================================================
-- 3) ADMIN: LIST REWARD CLAIM REQUESTS
--    Includes username, email, UUID and all requested rewards.
-- ============================================================
drop function if exists public.admin_list_reward_claims();

create function public.admin_list_reward_claims()
returns table (
  id bigint,
  user_id uuid,
  username text,
  email text,
  items jsonb,
  status text,
  created_at timestamptz,
  reviewed_at timestamptz,
  reviewed_by uuid
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'not_admin';
  end if;

  return query
  select
    r.id,
    r.user_id,
    coalesce(p.username, 'ไม่ทราบชื่อ')::text,
    coalesce(u.email, '')::text,
    r.items,
    r.status,
    r.created_at,
    r.reviewed_at,
    r.reviewed_by
  from public.reward_claim_requests r
  left join public.profiles p on p.id = r.user_id
  left join auth.users u on u.id = r.user_id
  order by case when r.status='pending' then 0 else 1 end,
           r.created_at desc;
end;
$$;

revoke all on function public.admin_list_reward_claims() from public;
grant execute on function public.admin_list_reward_claims() to authenticated;

-- ============================================================
-- 4) ADMIN: APPROVE / REJECT REWARD CLAIM
--    Rejecting returns the requested rewards to the player's
--    current inventory. Approving leaves them removed.
-- ============================================================
drop function if exists public.admin_review_reward_claim(bigint, boolean);

create function public.admin_review_reward_claim(
  p_claim_id bigint,
  p_approve boolean
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid;
  v_items jsonb;
  v_status text;
  v_current jsonb := '[]'::jsonb;
begin
  if not public.is_admin() then
    raise exception 'not_admin';
  end if;

  select user_id, items, status
    into v_user_id, v_items, v_status
  from public.reward_claim_requests
  where id = p_claim_id
  for update;

  if v_user_id is null then
    raise exception 'claim_not_found';
  end if;

  if v_status <> 'pending' then
    raise exception 'claim_already_reviewed';
  end if;

  if p_approve then
    update public.reward_claim_requests
    set status='approved',
        reviewed_at=now(),
        reviewed_by=auth.uid()
    where id=p_claim_id;
  else
    select coalesce(items, '[]'::jsonb)
      into v_current
    from public.player_inventory
    where user_id=v_user_id
    for update;

    insert into public.player_inventory(user_id, items, updated_at)
    values (v_user_id, coalesce(v_current,'[]'::jsonb) || coalesce(v_items,'[]'::jsonb), now())
    on conflict (user_id) do update
      set items = coalesce(public.player_inventory.items,'[]'::jsonb) || coalesce(excluded.items,'[]'::jsonb),
          updated_at = now();

    update public.reward_claim_requests
    set status='rejected',
        reviewed_at=now(),
        reviewed_by=auth.uid()
    where id=p_claim_id;
  end if;

  return case when p_approve then 'approved' else 'rejected' end;
end;
$$;

revoke all on function public.admin_review_reward_claim(bigint, boolean) from public;
grant execute on function public.admin_review_reward_claim(bigint, boolean) to authenticated;

-- ============================================================
-- 5) ADMIN: ADD / REMOVE COINS
--    Keeps the existing behavior: balance cannot go below 0.
-- ============================================================
drop function if exists public.admin_adjust_coins(uuid,bigint);

create function public.admin_adjust_coins(
  p_user_id uuid,
  p_delta bigint
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_new bigint;
begin
  if not public.is_admin() then
    raise exception 'not_admin';
  end if;

  if p_delta = 0 or abs(p_delta) > 1000000 then
    raise exception 'invalid_delta';
  end if;

  update public.profiles
  set coins = greatest(0, coins + p_delta),
      updated_at = now()
  where id = p_user_id
  returning coins into v_new;

  if v_new is null then
    raise exception 'profile_not_found';
  end if;

  return v_new;
end;
$$;

revoke all on function public.admin_adjust_coins(uuid,bigint) from public;
grant execute on function public.admin_adjust_coins(uuid,bigint) to authenticated;

notify pgrst, 'reload schema';
