-- Mystery Box: initial Supabase schema
-- Run this in Supabase SQL Editor.
-- This creates the online profile/history foundations only.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  avatar text,
  coins bigint not null default 0 check (coins >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.gacha_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  box_id text,
  box_name text,
  item_name text not null,
  rarity text,
  icon text,
  rolled_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.gacha_history enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles
for select to authenticated using (auth.uid() = id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own" on public.profiles
for insert to authenticated with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles
for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "history_select_own" on public.gacha_history;
create policy "history_select_own" on public.gacha_history
for select to authenticated using (auth.uid() = user_id);

drop policy if exists "history_insert_own" on public.gacha_history;
create policy "history_insert_own" on public.gacha_history
for insert to authenticated with check (auth.uid() = user_id);

create index if not exists gacha_history_user_rolled_idx
on public.gacha_history(user_id, rolled_at desc);

-- Automatic cleanup: keep only the last 7 days of history.
create or replace function public.cleanup_old_gacha_history()
returns void
language sql
security definer
set search_path = public
as $$
  delete from public.gacha_history
  where rolled_at < now() - interval '7 days';
$$;
